// app/components/Header.vue
<script lang="ts" setup>
import type { NavigationMenuItem } from '@nuxt/ui';



const navItems = ref<NavigationMenuItem[]>([
    {
        label: 'Animes',
        to: '/animes',
        // children: [
        //     {
        //         label: 'Top Anime',
        //         to: '/animes/top',
        //     },
        //     {
        //         label: 'Calendar',
        //         to: '/animes/calendar',
        //     },
        //     {
        //         label: 'Upcoming',
        //         to: '/animes/upcoming',
        //     },
        //     {
        //         label: 'This Season',
        //         to: '/animes?season=current',
        //     },
        // ],
    },
    {
        label: 'About',
        to: '/about',
    },
    {
        label: 'Discord',
        to: '/discord',
        trailingIcon: 'i-lucide-external-link',
    },
    {
        label: 'Blog',
        to: '/blog',
    },
    // {
    //     label: 'Manga',
    //     to: '/manga',
    //     children: [
    //         {
    //             label: 'Top Anime',
    //             to: '/manga/top',
    //         },
    //         {
    //             label: 'Calendar',
    //             to: '/manga/calendar',
    //         },
    //         {
    //             label: 'Upcoming',
    //             to: '/manga/upcoming',
    //         },
    //         {
    //             label: 'This Season',
    //             to: '/manga?season=current',
    //         },
    //     ],
    // },
])
</script>

<template>
    <header
        class="sticky top-0 z-50 w-full bg-neutral-900/55 backdrop-blur">
        <UContainer class="container flex h-15 max-w-screen-2xl items-center px-4 justify-between">

            <UContainer class="flex items-center gap-2 w-fit mx-0 px-0 sm:px-0 lg:px-0">
                <UTooltip :delay-duration="6000" text="❤️" :ui="{ text: 'text-md' }">
                    <NuxtLink to="/" class="flex items-center gap-2">
                        <img src="~/assets/images/app_icon.png" alt="App Icon" class="size-[50px]">
                        <h2 class="font-bold text-xl">{{ $t('common.appName') }}</h2>
                    </NuxtLink>
                </UTooltip>
            </UContainer>

            <UNavigationMenu :items="navItems" class="w-[45%]" />

            <UContainer class="flex items-center gap-2 w-fit mx-0 px-0 sm:px-0 lg:px-0">
                <SearchButton aria-label="advanced search" />
                <LanguageSwitcher aria-label="language selector" />
                <ColorModeButton aria-label="theme or colormode button" />
            </UContainer>

        </UContainer>
        <USeparator />
    </header>
</template>

// src/components/layout/header.tsx

"use client";

import { Github } from 'lucide-react';
import Link from 'next/link';
import Image from 'next/image';
import { ThemeToggle } from '@/components/layout/theme-toggle';
import { Button } from '@/components/ui/button';
import { LanguageSwitcher } from '@/components/layout/language-switcher';
import { useTranslations } from '@/lib/i18n/index.tsx';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { FaDiscord } from 'react-icons/fa';

export function Header() {
  const { t, translations } = useTranslations();

  return (
    <header className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
      <div className="container flex h-14 max-w-screen-2xl items-center px-4">
        <TooltipProvider delayDuration={5000}>
          <Tooltip>
            <TooltipTrigger asChild>
              <Link href="/" className="flex items-center space-x-2">
                <Image
                  src="/32x32.png"
                  alt={t('common.appName')[0] as string}
                  width={32}
                  height={32}
                />
                <span
                  className="font-bold text-xl header-app-name"
                  data-text-content={translations.common.appName as string}
                >
                  {translations.common.appName}
                </span>
              </Link>
            </TooltipTrigger>
            <TooltipContent>
              <p>❤️</p>
            </TooltipContent>
          </Tooltip>
        </TooltipProvider>
        
        <TooltipProvider delayDuration={1000}>
          <div className="ml-auto flex items-center space-x-2">
            <Tooltip>
              <TooltipTrigger asChild>
                <LanguageSwitcher />
              </TooltipTrigger>
              <TooltipContent>
                <p>{t('header.language')[0]}</p>
              </TooltipContent>
            </Tooltip>

            <Tooltip>
              <TooltipTrigger asChild>
                <Button variant="outline" size="icon" asChild className="h-9 w-9">
                  <Link href="https://github.com/anime-pack" target="_blank" rel="noopener noreferrer">
                    <Github className="h-[1.2rem] w-[1.2rem]" />
                    <span className="sr-only">{t('header.srGitHub')[0]}</span>
                  </Link>
                </Button>
              </TooltipTrigger>
              <TooltipContent>
                <p>{t('header.srGitHub')[0]}</p>
              </TooltipContent>
            </Tooltip>

            <Tooltip>
              <TooltipTrigger asChild>
                <Button variant="outline" size="icon" asChild className="h-9 w-9">
                  <Link href="https://discord.gg/Nv8UXpB36y" target="_blank" rel="noopener noreferrer">
                    <FaDiscord className="h-[1.2rem] w-[1.2rem]" />
                    <span className="sr-only">{t('header.srDiscord')[0]}</span>
                  </Link>
                </Button>
              </TooltipTrigger>
              <TooltipContent>
                <p>{t('header.srDiscord')[0]}</p>
              </TooltipContent>
            </Tooltip>

            <Tooltip>
              <TooltipTrigger asChild>
                <ThemeToggle />
              </TooltipTrigger>
              <TooltipContent align="end">
                <p>{t('header.srThemeToggle')[0]}</p>
              </TooltipContent>
            </Tooltip>
          </div>
        </TooltipProvider>
      </div>
    </header>
  );
}
