// src/components/layout/footer.tsx

export function Footer() {
  return (
    <footer className="py-6 md:px-8 md:py-0 border-t border-border/40">
      <div className="container flex flex-col items-center justify-center gap-4 md:h-20 md:flex-row">
        <div className="flex flex-col items-center text-center">
          <p className="text-balance text-sm leading-loose text-muted-foreground">
            © {new Date().getFullYear()} Anime Pack. All rights reserved.
          </p>
          <p className="text-balance text-xs leading-loose text-muted-foreground/80 mt-1">
            Anime Pack is an independent project and is not affiliated with, nor endorsed by, MyAnimeList or Discord.
          </p>
        </div>
      </div>
    </footer>
  );
}

// components/Footer.vue
<script lang="ts" setup>

</script>

<template>
    <footer>
        <div
            class="flex flex-col items-center justify-center py-4 text-sm text-gray-500 border-t border-white/10">
            <p>&copy; 2025 Anime Pack. All rights reserved.</p>
            <p class="mt-2 text-center">
                With ❤️ for the community.
            </p>
            <!-- <p class="mt-2">
                    <NuxtLink to="/legal/privacy-policy" class="text-blue-500 hover:underline">Privacy Policy</NuxtLink> |
                    <NuxtLink to="/legal/terms-of-service" class="text-blue-500 hover:underline">Terms of Service</NuxtLink>
                </p> -->
            <p>
                Anime Pack is an independent project and is not affiliated with, nor endorsed by, MyAnimeList or
                Discord.
            </p>
        </div>
    </footer>
</template>
